#!/bin/bash

STATE=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | cut -d: -f2 | sed 's/^\ \+//')
CHARGE=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | cut -d: -f2 | sed 's/^\ \+//')

echo "$STATE: $CHARGE"

